### ISSUE TITLE
implement GreptimeDBCluster CRD

### ISSUE THREAD

**Issue by zyy17** [GreptimeTeam/greptimedb-operator#1]
GreptimeDBCluster is the Kubernetes CRD that describe the desired state of GreptimeDB cluster. For example, we can describe our own greptimedb cluster as the following YAML:

```yaml
apiVersion: greptime.cloud/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: basic-gt-cluster
  namespace: default
spec:
  httpServicePort: 8080
  grpcServicePort: 9090
  frontend:
    image: greptime/frontend:v0.1-alpha
    replicas: 1
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  meta:
    image: greptime/meta:v0.1-alpha
    replicas: 3
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  datanode:
    image: greptime/datanode:v0.1-alpha
    replicas: 1
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
```

GreptimeDBCluster should describe the following state:

- describe the component spec(frontend/meta/datanode), including their service and storage spec;
- describe the specified cluster settings, like `httpServicePort`;
- describe the current status of cluster;
