### ISSUE TITLE
incorrect name for etcd cluster endpoint in documentation

### ISSUE THREAD

**Issue by logwiser** [GreptimeTeam/greptimedb-operator#237]
There seems to be an issue with the documentation

https://github.com/GreptimeTeam/greptimedb-operator/blob/main/examples/README.md
says
```
The following examples suppose that you have installed the etcd cluster in the etcd namespace with the service endpoint etcd.etcd-cluster.svc.cluster.local:2379
```

If the namespace is etcd, the endpoint is expected to have a DNS suffix of `etcd.svc.cluster.local` instead

Thus by extension, the example in https://github.com/GreptimeTeam/greptimedb-operator/blob/main/examples/cluster/basic/cluster.yaml is a bit incorrect.

Here is an example that worked better for me

# Create an etcd cluster in namespace called `meta`

```
helm upgrade --install \
	etcd-greptime oci://registry-1.docker.io/bitnamicharts/etcd \
--set replicaCount=3 \
--set auth.rbac.create=false \
--set auth.token.enabled=false \
--set serviceAccount.create=false \
--set serviceAccount.name=prometheus \
--set global.defaultStorageClass=standard-disk \
-n meta
````

# Note the etcd endpoint, which comes out to be `etcd-greptime.meta.svc.cluster.local:2379`

# Deploy greptimeDB in the namespace called `greptime-basic`
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: greptime-basic
  labels:
    mode: basic

---
apiVersion: greptime.io/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: basic
  namespace: greptime-basic
spec:
  base:
    main:
      image: greptime/greptimedb:latest
  frontend:
    replicas: 1
  meta:
    replicas: 1
    etcdEndpoints:
      - "etcd-greptime.meta.svc.cluster.local:2379"
  datanode:
    replicas: 1
```
